# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    #working_directory: ~/repo
    
    branches:
      only:
        - master
        - /rc-.*/

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      #TERM: dumb

    steps:
      - checkout

      - restore_cache:
            key: jars-{{ checksum "./build.gradle" }}-{{ checksum  "./build.gradle" }}
      - run: echo 'export TERM=dumb' >> $BASH_ENV
      
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "./build.gradle" }}-{{ checksum  "./compuconTaxi/build.gradle" }}
      - run:
          name: Clean
          command: ./gradlew clean
#      - run:
#          name: Lint
#          command: cd IGNrando && ./gradlew lintRelease
#      - run:
#          name: Prepare Lint Reports
#          command: >
#            cd IGNrando ;
#            mkdir lint_reports || true ;
#            for i in `find . -type d -maxdepth 1 -name 'ubicarta.*'` ; do
#              if [ -d $i/build/reports ] ; then
#                echo Store lint $i ;
#                mkdir lint_reports/$i || true ;
#                mv $i/build/reports/* lint_reports/$i ;
#              fi ;
#            done
#      - store_artifacts:
#          path: IGNrando/lint_reports/
#          destination: lint_reports/
#      - run:
#           name: Build Bundle
#           command: cd IGNrando && ./gradlew bundle -PdisablePreDex -DCI=${CIRCLE_CI} -Dversion-build=${CIRCLE_BUILD_NUM} 
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      # run: gradle test